model_name: "ComplexN3"
datasets:
  - dataset: "freebase15k"
    parameters:
      learning_rate: 0.05
      hidden_size: 200
      batch_size: 5000
      epochs: 1000
      optimizer: "adagrad"
      sampling: "uniform"
      neg_rate: 1
      lmbda: 0.0001