model_name: "CP"
datasets:
  - dataset: "freebase15k"
    parameters:
      learning_rate:  0.01
      hidden_size: 50
      batch_size: 128
      epochs: 50
      optimizer: "adagrad"
      sampling: "uniform"
      neg_rate: 1
      lmbda: 0.0001