model_name: "HoLE"
dataset: "freebase15k"
parameters:
  learning_rate: 0.1
  hidden_size: 150
  batch_size: 1200
  epochs: 1000
  margin: 0.2
  optimizer: "sgd"
  sampling: "uniform"
  neg_rate: 1
search_space:
  learning_rate:
    min: 0.00001
    max: 0.1
  l1_flag:
    - True
    - False
  hidden_size:
    min: 8
    max: 256
  batch_size:
    min: 8
    max: 4096
  margin:
    min: 0.0
    max: 2.0
  optimizer:
    - "adam"
    - "sgd"
    - "rms"
  epochs:
    - 10
