model_name: "InteractE"
datasets:
  - dataset: "freebase15k_237"
    parameters:
      learning_rate: 0.0001
      l1_flag: False
      feature_permutation: 1
      num_filters: 96
      kernel_size: 9
      reshape_height: 20
      reshape_width: 10
      input_dropout: 0.2
      feature_map_dropout: 0.5
      hidden_dropout: 0.3
      label_smoothing: 0.1
      batch_size: 128
      optimizer: "adam"
      neg_rate: 0

  - dataset: "wordnet18_rr"
    parameters:
      learning_rate: 0.001
      l1_flag: False
      feature_permutation: 2
      num_filters: 96
      kernel_size: 11
      reshape_height: 20
      reshape_width: 10
      input_dropout: 0.2
      feature_map_dropout: 0.2
      hidden_dropout: 0.3
      label_smoothing: 0.1
      batch_size: 128
      optimizer: "adam"
      neg_rate: 0

  - dataset: "yago3_10"
    parameters:
      learning_rate: 0.0001
      l1_flag: False
      feature_permutation: 4
      num_filters: 64
      kernel_size: 7
      reshape_height: 20
      reshape_width: 10
      input_dropout: 0.2
      feature_map_dropout: 0.2
      hidden_dropout: 0.3
      label_smoothing: 0.1
      batch_size: 128
      optimizer: "adam"
      neg_rate: 0

  - dataset: "freebase15k"
    parameters:
      learning_rate: 0.0001
      l1_flag: False
      feature_permutation: 1
      num_filters: 96
      kernel_size: 9
      reshape_height: 20
      reshape_width: 10
      input_dropout: 0.2
      feature_map_dropout: 0.5
      hidden_dropout: 0.3
      label_smoothing: 0.1
      batch_size: 128
      optimizer: "adam"
      neg_rate: 0