model_name: "KG2E"
datasets:
  - dataset: "freebase15k"
    parameters:
      learning_rate: 0.01
      l1_flag: True
      hidden_size: 50
      batch_size: 1440
      epochs: 1000
      margin: 4.0
      optimizer: "sgd"
      sampling: "uniform"
      cmax: 0.05
      cmin: 5.00
      neg_rate: 1