dataset: "freebase15k"
parameters:
  learning_rate: 0.01
  ent_hidden_size: 100
  rel_hidden_size: 100
  batch_size: 128
  epochs: 1000
  margin: 1.0
  optimizer: "adam"
  sampling: "uniform"
  neg_rate: 1
  lmbda: 0.0001
search_space:
  learning_rate:
    min: 0.00001
    max: 0.1
  l1_flag:
    - True
    - False
  ent_hidden_size:
    min: 8
    max: 64
  rel_hidden_size:
    min: 8
    max: 64
  batch_size:
    min: 8
    max: 4096
  margin:
    min: 0.0
    max: 2.0
  optimizer:
    - "adam"
    - "sgd"
    - "rms"
  epochs:
    - 10
