dataset: "freebase15k"
parameters:
  learning_rate: 0.0001
  hidden_size: 1000
  batch_size: 1024
  epochs: 1000
  margin: 24.0
  optimizer: "adam"
  sampling: "adversarial_negative_sampling"
  alpha: 1.0
  neg_rate: 16
search_space:
  learning_rate:
    min: 0.00001
    max: 0.1
  l1_flag:
    - True
    - False
  hidden_size:
    min: 8
    max: 256
  batch_size:
    min: 8
    max: 4096
  margin:
    min: 0.0
    max: 2.0
  optimizer:
    - "adam"
    - "sgd"
    - "rms"
  epochs:
    - 10
