model_name: "SLM"
dataset: "freebase15k"
parameters:
  learning_rate: 0.01
  l1_flag: True
  ent_hidden_size: 64
  rel_hidden_size: 32
  batch_size: 128
  epochs: 1000
  margin: 1.0
  optimizer: "adam"
  sampling: "uniform"
  neg_rate: 1
search_space:
  learning_rate:
    min: 0.00001
    max: 0.1
  l1_flag:
    - True
    - False
  ent_hidden_size:
    min: 8
    max: 256
  rel_hidden_size:
    min: 8
    max: 256
  batch_size:
    min: 8
    max: 4096
  margin:
    min: 0.0
    max: 2.0
  optimizer:
    - "adam"
    - "sgd"
    - "rms"
  epochs:
    - 10
