model_name: "SME_BL"
datasets:
  - dataset: "freebase15k"
    parameters:
      learning_rate: 0.1
      l1_flag: True
      hidden_size: 50
      batch_size: 50000
      epochs: 1000
      optimizer: "adam"