model_name: "TransD"
datasets:
  - dataset: "freebase15k"
    parameters:
      learning_rate: 0.001
      l1_flag: False
      ent_hidden_size: 50
      rel_hidden_size: 50
      batch_size: 200
      epochs: 1000
      margin: 1.0
      optimizer: "sgd"
      sampling: "uniform"
      neg_rate: 1